# Copyright (C) 2015 Birchbox Inc
# See LICENSE for details
FROM afskbpw2015/kdc:latest
MAINTAINER Thomas Kula <kula@birchbox.com>
LABEL Description="A base kdc image, with kadmind"
RUN DEBIAN_FRONTEND='noninteractive' apt-get install -y krb5-admin-server

